#!/bin/bash -ex

[ $UID -ne 0 ] && echo "This script should get executed as root. Otherwise file special permissions are not set correctly." >&2

TAR_DATE=${TAR_DATE:-$(date +'%Y.%m.01')}
ARCHLINUX_ARCH=x86_64
ARCHLINUX_MIRR=https://archive.archlinux.org/iso

mkdir -p Dockerfiles/basement/arch-rootfs
mkdir -p tarballs/${TAR_DATE}

# Download tarball, signature and sha1sums.txt
# Verify sha1sum for tarball
(
cd tarballs/${TAR_DATE} \
&& wget -q --no-cookies \
	${ARCHLINUX_MIRR}/${TAR_DATE}/archlinux-bootstrap-${TAR_DATE}-${ARCHLINUX_ARCH}.tar.gz{,.sig} \
	${ARCHLINUX_MIRR}/${TAR_DATE}/sha1sums.txt \
&& grep archlinux-bootstrap-${TAR_DATE}-${ARCHLINUX_ARCH}.tar.gz sha1sums.txt \
	| sha1sum --check -
)

# Verify the data by its gpg-signature
# https://wiki.archlinux.org/index.php/Category:Getting_and_installing_Arch
gpg --keyserver-options auto-key-retrieve \
	--verify tarballs/${TAR_DATE}/archlinux-bootstrap-${TAR_DATE}-${ARCHLINUX_ARCH}.tar.gz.sig

tar xz \
	-f tarballs/${TAR_DATE}/archlinux-bootstrap-${TAR_DATE}-${ARCHLINUX_ARCH}.tar.gz \
	--strip-components=1 \
	--directory=./Dockerfiles/basement/arch-rootfs \
	root.${ARCHLINUX_ARCH}/

for repo in base::squash base:full:squash base-devel::nosquash; do
	IFS=: read repo tag opt <<< $repo
	docker build -f ./Dockerfiles/basement/Dockerfile.${repo}${tag:+_$tag} -t archimg-${repo}${tag:+_$tag}-currenttar ./Dockerfiles/basement
	if [ "${opt}" == "squash" ]; then
		docker-squash -t archimg-${repo}${tag:+_$tag}-currenttar archimg-${repo}${tag:+_$tag}-currenttar
	fi
done
