#!/bin/bash -ex

TAR_DATE="$(date --date="${1:-"now"}" +'%Y.%m').01"
ARCHLINUX_ARCH=x86_64
ARCHLINUX_MIRR=https://archive.archlinux.org/iso

mkdir -p arch-rootfs
mkdir -p tarballs/${TAR_DATE}


# Download tarball, signature and sha1sums.txt
# Verify sha1sum for tarball
(
cd tarballs/${TAR_DATE} \
&& wget -q --no-cookies \
	${ARCHLINUX_MIRR}/${TAR_DATE}/archlinux-bootstrap-${TAR_DATE}-${ARCHLINUX_ARCH}.tar.gz{,.sig} \
	${ARCHLINUX_MIRR}/${TAR_DATE}/sha1sums.txt \
&& grep archlinux-bootstrap-${TAR_DATE}-${ARCHLINUX_ARCH}.tar.gz sha1sums.txt \
	| sha1sum --check -
)

# Verify the data by its gpg-signature
# https://wiki.archlinux.org/index.php/Category:Getting_and_installing_Arch
gpg --keyserver-options auto-key-retrieve \
	--verify tarballs/${TAR_DATE}/archlinux-bootstrap-${TAR_DATE}-${ARCHLINUX_ARCH}.tar.gz.sig

sudo tar xz \
	-f tarballs/${TAR_DATE}/archlinux-bootstrap-${TAR_DATE}-${ARCHLINUX_ARCH}.tar.gz \
	--strip-components=1 \
	--directory=./arch-rootfs \
	root.${ARCHLINUX_ARCH}/
