#!/bin/bash -ex

ORGA=archimg
TAR_DATE=${TAR_DATE:-$(date +'%Y.%m.01')}

renamed_push(){
	docker tag "${1}" "${2}"
	docker push "${2}"
}

for repo in base base:full base-devel; do
	IFS=: read repo tag <<< $repo
	docker push ${ORGA}/${repo}:${tag:+$tag-}${TAR_DATE}
	docker push ${ORGA}/${repo}${tag:+:$tag}
done

# Manuals for base/ stuff
renamed_push ${ORGA}/base:${TAR_DATE}       base/archlinux:${TAR_DATE}
renamed_push ${ORGA}/base                   base/archlinux
renamed_push ${ORGA}/base-devel:${TAR_DATE} base/devel:${TAR_DATE}
renamed_push ${ORGA}/base-devel             base/devel
