#!/bin/bash -ex

ORGA=archimg
TAR_DATE=${TAR_DATE:-$(date +'%Y.%m.01')}

for repo in base base-devel; do
	docker tag archimg-${repo}-currenttar ${ORGA}/${repo}:${TAR_DATE}
	docker push ${ORGA}/${repo}:${TAR_DATE}
done

# Manuals for base/ stuff
docker tag archimg-base-currenttar       base/archlinux:${TAR_DATE}
docker tag archimg-base-devel-currenttar base/devel:${TAR_DATE}
docker push base/archlinux:${TAR_DATE}
docker push base/devel:${TAR_DATE}
