#!/bin/bash -ex

for repo in base base:full base-devel; do
	IFS=: read repo tag <<< $repo
	docker build -f ./Dockerfiles/updates/Dockerfile.${repo}${tag:+_$tag} -t ${ORGA}-${repo}${tag:+_$tag}-latest ./Dockerfiles/updates
done
